name: Deploy to GitHub Pages

on:
  push:
    branches:
      - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.19.0'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies and build
        run: |
          cd frontend-app
          npm install
          npm run build

      - name: Deploy App
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.MY_PAT }}
          build_configuration: staging
          base_href: ./
          deploy_branch: gh-pages
          angular_dist_build_folder: frontend-app/dist

permissions:
  contents: write