name: Deploy to GitHub Pages

on:
  push:
    branches:
      - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.19.0'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: |
          cd frontend-app
          npm install

      - name: Deploy App
        uses: JamesIves/github-pages-deploy-action@releases/v3
        env:
          ACCESS_TOKEN: ${{ secrets.MY_PAT }}
          BASE_BRANCH: develop
          BRANCH: gh-pages
          FOLDER: frontend-app/dist/frontend-app
          BUILD_SCRIPT: npm run build
