name: Deploy to GitHub Pages

on:
  push:
    branches:
      - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.19.0'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies and build
        run: |
          cd frontend-app
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd frontend-app
          git config user.name "AganDurm"
          git config user.email "durmisevicagan@outlook.de"
          npx angular-cli-ghpages --dir=dist/browser --no-silent
          ls dist
          ls dist/*
        env:
          GH_TOKEN: ${{ secrets.MY_PAT }}
